### ISSUE TITLE
Make Discord App ID configurable

### ISSUE THREAD

**Issue by nekowinston** [nekowinston/mpd-rich-presence#3]
Similar to how we can choose a custom Last.fm API, I should allow custom Discord App credentials.

Requested by @AnubisNekhet

**Comment by nathanielevan** [comment]
I'll take this up -- this should be simple enough. In the YAML config file, do I put the variable for Discord App ID under `rich_presence`, or as a top-level key? I'll make a pull request ASAP.

**Comment by nekowinston** [comment]
I think it would make sense as a key under `rich_presence`.
